### ISSUE TITLE
Support scenes ancestry -- go_back()

### ISSUE THREAD

**Issue by Goutte** [glass-brick/Scene-Manager#16]
**Is your feature request related to a problem? Please describe.**
I've found it convenient to store (on-demand, so it adds new parameters to the scene switch API) the scene ancestry (instead of immediately `queue_free`), so we can `go_back()` to the previous scene (and free the current), optionally passing a value.

**Describe the solution you'd like**
A scene ancestry (a stack), filled if switching to a scene is provided an extra parameter `add_current_to_ancestry`.  And methods in SceneManager to go back in the stack.

**Describe alternatives you've considered**
I made my own scene manager, and it's terrible.

**Comment by jabsatz** [comment]
This is an interesting idea, but I'm actually not sure how that would work exactly (in particular, I'm not sure how we would handle keeping a scene without freeing it from memory). Can you describe your particular use-case a bit better?

**Comment by jabsatz** [comment]
Closing for lack of response
