### ISSUE TITLE
Change scene with PackedScene instead of string

### ISSUE THREAD

**Issue by myin142** [glass-brick/Scene-Manager#17]
**Is your feature request related to a problem? Please describe.**
I usually don't like to call the `get_tree().change_scene()` method because it takes a string. If I ever move or rename the scene I have to find all usages of it and do the same. That's why I always use `get_tree().change_scene_to()` with a `PackedScene`. That way it will always be automatically updated whenever I change the path of the scene.

**Describe the solution you'd like**
Currently only the `change_scene()` is possible with this plugin. I would be nice if we also have the other option available

**Comment by jabsatz** [comment]
This is definitely a valid use case. I'll work on it when I have some time, or if you want to implement a solution you're free to open a pull request.

**Comment by jabsatz** [comment]
To be clear, the solution I have in mind is to make `SceneManager.change_scene()` take either a `String` or a `PackedScene` as a parameter, not to make a whole new method, in order to keep the API as small as possible
