### ISSUE TITLE
The VideoMemory fill up (loading) is not included in the loading screen.

### ISSUE THREAD

**Issue by ksjfhor** [glass-brick/Scene-Manager#20]
**Is your feature request related to a problem? Please describe.**
This is kinda a problem, but more of a nice-to-have.
The VideoMemory fill up (loading) is not included in the loading screen.

So when my Project is getting loaded, it stays at 0%, but in the debugger I can see that the VideoMemory is getting filled (up to nearly 4GB, yeah I got a lot of Textures) and after all is loaded into the VideoMemory, then the percentage are counted up.

**Describe the solution you'd like**
The percentage should be including that the Video Memory is getting filled.

**Describe alternatives you've considered**
Maybe a VideoMemoryFillSize variable could be set to like 4GB (the dev need to know how much their going to need) and then maybe we could check how much is already filled.

**Additional context**
![0%](https://user-images.githubusercontent.com/87974401/189852347-6bac1193-65cf-4371-afb2-410407644b04.PNG)
I took a screenshot before the VideoMemory was filled, so you can see it stays for like 30 seconds at 0%.

**Comment by ksjfhor** [comment]
Sorry, I was surly not that clear.

The Loading Bar starts only when the Videomemory is filled, in my case roughly 4GB.
Before the VideoMemory is filled, the Bar sits at 0%.

I made a small Video to better show what is going on: 
https://youtu.be/HaOsnYHhHOM

**Comment by jabsatz** [comment]
Okay, I see the issue now.

May I ask how the loading bar is implemented? And where exactly you use the SceneManager?

**Comment by ksjfhor** [comment]
I am so stupid and sorry for your time left to me, this is not the correct addon for this issues .... 
Sorry !

**Comment by jabsatz** [comment]
No problem, take care!
