### ISSUE TITLE
RFC: Better API for custom animations

### ISSUE THREAD

**Issue by jabsatz** [glass-brick/Scene-Manager#23]
# Goal

This is an RFC (Request for comments) on improving the custom animations API. We're looking for your thoughts on how you use this feature, and how you think it could be improved. If you have encountered any issues not mentioned here, feel free to comment them as well.

# Current overview

Currently, the workflow involves:
1. Creating a new Scene with an AnimationPlayer as root
2. Set RESET and custom animations on that player
3. Manually run SceneManager.set_animation_player(YourAnimationPlayerScene) once, early in your game.

I think the first two steps are good, since they allow users flexibility to move their files around as they please and create the scene as they like it, however the third step seems inconvenient.

It definitely gets the job done, but it creates two things I don't like:
1. It makes users have to call `set_animation_player` on a script that is potentially completely unrelated to scene transitions (and potentially makes users have to create a script solely for this purpose)
2. It adds a somewhat unnecesary API method (since it's only called once by a fraction of users)

# Proposed Solutions

I can think of two alternatives that would solve these issues:

## Plugin popup solution
There are plugins around which will add custom screens to the godot editor itself to configure plugin settings, such as Dialogic does with their dialogue preview options. We could implement something similar in a much smaller scale (perhaps a simple popup with a text input?) to set the path of the animation_player. We would save this data into a .tres file that is loaded when the game starts, so we instantly pick up the path and load it into SceneManager.

The main disadvantage of this approach is basically the difficulty of implementing it. In my experience doing similar plugins for Godot 3, these sorts of "Editor plugins" are a bit annoying to implement since the developer has to reload the plugin every time they make a change and the changes don't always apply on first try. I'm also not sure if a popup triggered from, for example, one of Godot's menu dropdowns at the top of the editor, can be achieved. The closest I've seen is a new "main screen" (such as the 2D, 3D, Script and AssetLib tabs), which seems a little intrusive and way too big for the use-case I'm describing.

## Hardcoded path solution
We could set a "hardcoded" path to the AnimationPlayer scene. This could be something like `res://SceneManagerAnimationPlayer.tscn` or `res://addons/scene_manager/SceneManagerAnimationPlayer.tscn`, and we could even have both with the second one as a fallback for the first one. If this was implemented, this would work _in addition_ to the current `set_animation_player` method, so the user could either use these paths OR set a custom one. This would also allow the (in my opinion) not recommended option of manually modifying the scene_manager code to just add paths directly there.

The disadvantages for this approach are several, it's more of a _patch_ than a solution, since we're only adding a couple of places were users CAN just drop the AnimationPlayer and have it work instantly. However it's much easier to implement and it does solve the issue for some people.

**Comment by Mickeon** [comment]
Can it not be a custom Project Setting at worst?

**Comment by jabsatz** [comment]
That's actually a better idea, I hadn't thought of that

**Comment by jabsatz** [comment]
Animations seem to be mostly working properly, and there's not much demand for this feature. I will be closing it for now.
