### ISSUE TITLE
Godot 4 - shader parameters warning

### ISSUE THREAD

**Issue by jecovier** [glass-brick/Scene-Manager#24]
**Describe the bug**
when I use this addon in Godot 4 I got a lot of warnings due to the shader parameters using an old name convention. It's not critical but it can be avoided updating the way this addon sets shader parameters

**To Reproduce**
1. add this addon to a new project in Godot 4.0.1+
2. add a transition in a scene
3. look the debugger console in Godot

**Expected behavior**
I expect the console doesn't show any addon warning

**Screenshots**
![Captura desde 2023-04-16 06-00-33](https://user-images.githubusercontent.com/3135068/232305479-49815758-0431-47ce-802c-ab4a201c27b7.png)

**Comment by jecovier** [comment]
Please consider merging the PR I created with the solution for this issue:
[PR-25](https://github.com/glass-brick/Scene-Manager/pull/25)

**Comment by jabsatz** [comment]
Thanks for writing the PR, it looks good, I'll merge it now and release a new version with it soon 👍
