### ISSUE TITLE
change_scene doesn't work with PackedScene

### ISSUE THREAD

**Issue by Ubiguchi** [glass-brick/Scene-Manager#26]
**Describe the bug**
change_scene fails when passed a PackedScene as it's looking for a resource path

**To Reproduce**
1. var scene_path = "res://world.tscn"
2. var packed_scene = load(scene_path) 
3. SceneManager.change_scene(packed_scene) 
4. Assertion failes: Path must be string in change_scene

**Expected behavior**
Function as per passing in path

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by jabsatz** [comment]
Thanks for reporting, I'll probably fix this during the weekend. If you've got a fix you'd like to commit before that, it's also welcome 😄
