### ISSUE TITLE
[Docs] Entity Singletons Features example missing options in Godot 4.1.1

### ISSUE THREAD

**Issue by JoelCreatesGames** [glass-brick/Scene-Manager#31]
**Describe the bug**
The documentation for https://github.com/glass-brick/Scene-Manager/wiki/Features#entity-singletons is seemingly inaccurate in the gif, I'm thinking it may be relevant to 3.x and not 4.x versions.

I believe this has changed to be relying on a group `scene_manager_entity_nodes` being applied (rather than the checkbox) and `entity_name` metadata applied on the node for
- https://github.com/glass-brick/Scene-Manager/blob/7ae7eea7d69273bda0619618ddde545d6ca92528/demo/test.gd#L7
- https://github.com/glass-brick/Scene-Manager/blob/7ae7eea7d69273bda0619618ddde545d6ca92528/demo/test.tscn#L16
- https://github.com/glass-brick/Scene-Manager/blob/7ae7eea7d69273bda0619618ddde545d6ca92528/demo/test.tscn#L25

Also noting the API docs seem to be referencing the non existent fields https://github.com/glass-brick/Scene-Manager/wiki/API-(Godot-4)#get_entity

I was thinking about editing the wiki myself, but wanted to be sure that my assumptions/investigations were correct before doing so

**Comment by jabsatz** [comment]
The entity singleton feature was broken in the 4.x update and we expected to remove it entirely since it seems a bit outside the scope of what the addon should do, and the addition of scene unique node names in godot 4 has made it less useful in general.
